apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventstreams
  namespace: openshift-operators
spec:
  channel: v12.2
  name: ibm-eventstreams
  source: ibm-eventstreams
  sourceNamespace: openshift-marketplace
