apiVersion: integration.ibm.com/v1beta1
kind: IntegrationAssembly
metadata:
  name: ia-test-product-ir
  labels:
    backup.integration.ibm.com/component: integrationassembly
  namespace: tools
spec:
  license:
    accept: true
    license: L-JTPV-KYG8TF
    use: CloudPakForIntegrationNonProduction
  version: 16.1.0
  managedInstances:
    list: []
  managedIntegrations:
    list:
      - kind: Product
        metadata:
          name: jgr-ace-ivt-ia
        spec:
          state: Published
          definition:
            product: 1.0.0
            info:
              title: ACEIVTAPI
              name: jgr-ace-ivt-api
              version: '1.0.0'
            plans:
              default-plan:
                rate-limits:
                  default:
                    value: 100/1hour
                title: Default Plan
                description: Default Plan
                approval: false
          apis:
            integrationRuntimes:
              - name: jgr-ace-ivt-ia
                security:
                  type: NoOp
          share:
            apim:
              credentialsSecret: apim-credentials
              providerOrg: cp4i-demo-org
              catalog: sandbox
      - kind: IntegrationRuntime
        metadata:
          name: jgr-ace-ivt-ia
        spec:
          license:
            accept: true
            license: L-XRNH-47FJAW
            use: CloudPakForIntegrationNonProduction
          version: '12.0'
          barURL:
            - >-
              https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/jgr-cp4i-aceivt.bar
          configurations:
            - github-barauth
  storage:
    readWriteOnce:
      class: ${OCP_BLOCK_STORAGE}
