apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-ivt-topic
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-es-demo-topic
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-mq-2-es-demo-topic
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cp4i-es-2-mq-demo-topic
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: apic-analytics-offload-topic
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: customer-service-feedback
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: service-at-risk
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: '86400000'