kind: Service
apiVersion: v1
metadata:
  name: qmgr-ext-np-nosni-ibm-mq
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - name: qmgr
      protocol: TCP
      port: 1414
      targetPort: 1414
      nodePort: 31414
  internalTrafficPolicy: Cluster
  type: NodePort
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    statefulset.kubernetes.io/pod-name: qmgr-ext-np-ibm-mq-0