apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-demo-ini
  labels:
    assembly.integration.ibm.com/tools.jgr-demo: 'true'
data:
  mq-demo-resources.ini: |
    TuningParameters:
      ExpiryInterval=350
    Service:
      Name=AuthorizationService
      EntryPoints=14
      SecurityPolicy=UserExternal