kind: ConfigMap
apiVersion: v1
metadata:
  name: webui-config
data:
  web.cfg: |-
    web-mgmt
      admin-state "enabled"
      local-address "0.0.0.0" "9090"
      save-config-overwrite
      idle-timeout 600
      ssl-config-type server
      no disable-csrf
      enable-sts
    exit
    EOF