apiVersion: v1
kind: Service
metadata:
  name: dp-demo-datapower
spec:
  selector:
    app.kubernetes.io/component: datapower
    app.kubernetes.io/instance: cp4i-dp-dp-demo
  ports:
  - protocol: TCP
    port: 2999
    targetPort: 2999
    name: gw-probe-port
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: apic-gw-mgmt
  - protocol: TCP
    port: 5554
    targetPort: 5554
    name: rmi-port
  - protocol: TCP
    port: 9090
    targetPort: 9090
    name: webgui-port
  - protocol: TCP
    port: 9443
    targetPort: 9443
    name: api-gw-svc
  - protocol: TCP
    port: 9091
    targetPort: 9091
    name: user-port