apiVersion: v1
kind: Service
metadata:
  name: mailpit-smtp
  namespace: mailpit
spec:
  ports:
  - port: 1025
    protocol: TCP
    targetPort: 1025
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  selector:
    app: mailpit
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit-ui
  namespace: mailpit
spec:
  ports:
  - port: 8025
    protocol: TCP
    targetPort: 8025
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  selector:
    app: mailpit
  sessionAffinity: None
  type: ClusterIP