apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mailpit-ui
  namespace: mailpit
spec:
  to:
    kind: Service
    name: mailpit-ui
    weight: 100
  port:
    targetPort: 8025
  wildcardPolicy: None