apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations:
    apiconnect-operator/backups-not-configured: 'true'
  labels:
    backup.apiconnect.ibm.com/component: apiconnectcluster
  name: apim-demo
spec:
  analytics:
    mtlsValidateClient: true
  license:
    accept: true
    license: L-WPTV-3V8RK2
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  portal:
    mtlsValidateClient: true
  profile: n1xc7.m48
  version: 10.0.9.0
  storageClassName: ${OCP_BLOCK_STORAGE}
  management:
    billing:
      enabled: true
    discovery:
      enabled: true
      proxyCollectorEnabled: true
    governance:
      enabled: true
    testAndMonitor:
      enabled: true
      autoTestEnabled: true
  gateway:
    podAutoScaling:
      method: HPA
      hpa:
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 50