kind: SwitchServer
apiVersion: appconnect.ibm.com/v1beta1
metadata:
  labels:
    backup.appconnect.ibm.com/component: switchserver
  name: ace-switch-server
spec:
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: CloudPakForIntegrationNonProduction
  version: '13.0'