apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: jgr-designer-sfleads
  labels:
    assembly.integration.ibm.com/tools.jgr-demo: 'true'
spec:
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: CloudPakForIntegrationNonProduction
  template:
    spec:
      containers:
        - name: runtime
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  replicas: 1
  version: '13.0'
  barURL: 
    - >-
      https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/${BAR_FILE}
  configurations:
    - github-barauth