apiVersion: events.ibm.com/v1beta1
kind: EventProcessing
metadata:
  name: ep-demo
spec:
  license:
    accept: true
    license: L-CYBH-K48BZQ
    use: EventAutomationNonProduction
  flink:
    endpoint: 'ea-flink-demo-rest:8081'
  authoring:
    authConfig:
      authType: ${EP_AUTH_TYPE}
    storage:
      storageClassName: ${OCP_BLOCK_STORAGE}
      type: persistent-claim
      size: 100M
    template:
      pod:
        spec:
          containers:
            - name: backend
              env:
                - name: JAVA_TOOL_OPTIONS
                  value: '-Djavax.net.ssl.trustStore=/opt/ibm/sp-backend/certs/eventautomation.jks -Djavax.net.ssl.trustStorePassword=eventautomationstore'
              volumeMounts:
                - mountPath: /opt/ibm/sp-backend/certs
                  name: truststore
          volumes:
            - name: truststore
              secret:
                items:
                  - key: eventautomation.jks
                    path: eventautomation.jks
                secretName: eventautomation-truststore