apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: qmgr-ext-np
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    use: NonProduction
  queueManager:
    name: QMGREXTNP
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    route:
      enabled: false
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: ${OCP_BLOCK_STORAGE}
    availability:
      type: SingleInstance
    mqsc:
      - configMap:
          name: mq-demo-mqsc
          items:
            - mq-demo-resources.mqsc
  version: ${MQ_VERSION}
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true