apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apic-gateway
  namespace: tools
spec:
  commonName: api-gateway-service
  dnsNames:
    - ${APIC_HOST}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: apic-gateway-tls