type: 'per_query'
title: 'JGR Demo Rule'
enabled: true
data_source: 'apievents'
schedule:
  schedule_type: 'interval'
  period_interval: 1
  period_unit: 'MINUTES'
filters:
  - contains:
      status_code: '40'
timeframe: '1m'
triggers:
  - title: 'My trigger'
    severity: 2
    condition:
      operator: 'gt'
      value: 1
    actions:
      - title: 'My Action'
        destination_id: '${DESTINATION_ID}'
        message: "{\n  \"email\": \"user@cp4.demo.net\",\n  \"severity\": 1,\n  \"subject\": \"APIs failing with 40x.\",\n  \"body\": \"Attention needed.\"\n}"
        subject: 'test'
        throttle_enabled: false