apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dpwebui-route
spec:
  host: "dpwebui-${NS_NAME}.${STACK_HOST}"
  to:
    kind: Service
    name: ${INST_NAME}-datapower
    weight: 100
  port:
    targetPort: webgui-port
  tls:
    termination: passthrough
  wildcardPolicy: None