apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${QMGR_NAME}-selfsigned-cert
  namespace: ${QMGR_NAMESPACE}
spec:
  commonName: ${QMGR_NAME}-app
  secretName: ${QMGR_NAME}-tls-secret
  isCA: false
  dnsNames:
    - ${QMGR_NAME}-ibm-mq.${QMGR_NAMESPACE}.svc
    - ${QMGR_NAME}-ibm-mq.${QMGR_NAMESPACE}.svc.cluster.local
    - ${QMGR_NAME}-ibm-mq-qm-${QMGR_NAMESPACE}.${OCP_CLUSTER_DOMAIN}
    - ${QMGR_NAME}-ibm-mq-web-${QMGR_NAMESPACE}.${OCP_CLUSTER_DOMAIN}
  issuerRef:
    name: ${QMGR_NAME}-ca-issuer