apiVersion: keycloak.integration.ibm.com/v1beta1
kind: IntegrationKeycloakClient
metadata:
  name: ep-demo-ibm-ep-keycloak
spec:
  client:
    redirectUris:
      - 'https://${EP_NAME}-ibm-ep-rt-${EP_NS}.${OCP_FQDN}/callback'
      - 'https://${EP_NAME}-ibm-ep-rt-${EP_NS}.${OCP_FQDN}/logout/callback'
    serviceAccountsEnabled: true
    clientId: ibm-ep-${EP_NS}-${EP_NAME}
    optionalClientScopes:
      - offline_access
    defaultClientScopes:
      - profile
      - openid
      - email
    implicitFlowEnabled: false
    publicClient: false
    standardFlowEnabled: true
    protocolMappers:
      - config:
          access.token.claim: 'true'
          claim.name: effectiveRoles
          id.token.claim: 'true'
          jsonType.label: String
          multivalued: 'true'
          userinfo.token.claim: 'true'
          usermodel.clientRoleMapping.clientId: ${CP4I_KC_CLIENT_ID}
        name: cloud-pak-level-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-client-role-mapper
      - config:
          access.token.claim: 'true'
          claim.name: effectiveRoles
          id.token.claim: 'true'
          jsonType.label: String
          multivalued: 'true'
          userinfo.token.claim: 'true'
          usermodel.clientRoleMapping.clientId: ibm-ep-${EP_NS}-${EP_NAME}
        name: ep-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-client-role-mapper
    directAccessGrantsEnabled: false
  roles:
    - name: user
  scopeMappings: {}