apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dpwebui-route
spec:
  host: "dpwebui-${NS_NAME}.${STACK_HOST}"
  to:
    kind: Service
    name: gwv6-datapower
  port:
    targetPort: 9090
  tls:
    termination: passthrough