apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaBridge
metadata:
  name: ${INST_NAME}
  labels:
    eventstreams.ibm.com/cluster: ${ES_INST_NAME}
spec:
  authentication:
    type: scram-sha-512
    username: ${ES_USER}
    passwordSecret:
      secretName: ${ES_USER}
      password: password
  bootstrapServers: ${ES_BOOTSTRAP_SERVER}
  http:
    port: 8080
  replicas: 1
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: ${ES_INST_NAME}-cluster-ca-cert
  template:
    bridgeContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true