apiVersion: v1
kind: ConfigMap
metadata:
  name: ${ES_INST_NAME}-ibm-es-discovery-endpoints
  namespace: ${ES_NAMESPACE}
data:
  endpoints.json: |-
    {
      "instances": [
        {
          "name": "${EEM_INST_NAME}",
          "type": "event-endpoint-manager",
          "server": {
            "host": "${EEM_API_HOST}",
            "port": 443,
            "ssl": true,
            "certificates": ["${EEM_CERTIFICATE}"]
          },
          "additional-info": {
            "eem-ui-url": "${EEM_UI_URL}"
          }
        }
      ]
    }
