apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dpuser-route
  labels:
    app.kubernetes.io/component: http
spec:
  host: "dpuser-${NS_NAME}.${STACK_HOST}"
  to:
    kind: Service
    name: ${INST_NAME}-datapower
  port:
    targetPort: user-port
  wildcardPolicy: None