apiVersion: v1
kind: Secret
metadata:
  name: apim-credentials
  namespace: tools
type: Opaque
stringData:
  base_url: ${APIC_BASE_URL}
  grant_type: api_key
  api_key: ${APIC_API_KEY}
  disable_trust: 'true'
  trusted_cert: |-
${APIC_TRUSTED_CERT}