apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: cp4i-navigator
spec:
  integrationAssistant:
    enabled: true
  license:
    accept: true
    license: L-CYPF-CRPF3H
  replicas: 1
  version: 16.1.2