apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations:
    apiconnect-operator/backups-not-configured: 'true'
  labels:
    backup.apiconnect.ibm.com/component: apiconnectcluster
  name: apim-demo
spec:
  analytics:
    mtlsValidateClient: true
  license:
    accept: true
    license: L-RAWZ-DSFFFV
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  portal:
    mtlsValidateClient: true
  profile: n1xc16.m72
  version: 10.0.10.0
  storageClassName: ${OCP_BLOCK_STORAGE}
  management:
    discovery:
      enabled: true
      proxyCollectorEnabled: true
    governance:
      enabled: true
    testAndMonitor:
      enabled: true
      autoTestEnabled: true