apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: es-demo
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
    assembly.integration.ibm.com/tools.jgr-demo: 'true'
spec:
  version: latest
  license:
    accept: true
    license: L-CYPF-CRPF3H
    use: CloudPakForIntegrationNonProduction
  adminApi: {}
  adminUI:
    authentication:
      - type: integrationKeycloak
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    kafka:
      replicas: 3
      authorization:
        type: simple
      config:
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3        
        auto.create.topics.enable: true
        default.replication.factor: 1
        min.insync.replicas: 1
      listeners:
        - name: authsslsvc
          port: 9095
          type: internal
          tls: true
          authentication:
            type: scram-sha-512
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: minimal-prod-metrics-config
    nodePools:
      - name: kafka
        replicas: 3
        roles:
          - broker
        storage:
          type: persistent-claim
          size: 50Gi
          class: ${OCP_BLOCK_STORAGE}
      - name: controller
        replicas: 3
        roles:
          - controller
        storage:
          type: persistent-claim
          size: 2Gi
          class: ${OCP_BLOCK_STORAGE}
    entityOperator:
      topicOperator: {}
      userOperator: {}