apiVersion: appconnect.ibm.com/v1beta1
kind: DesignerAuthoring
metadata:
  labels:
    backup.appconnect.ibm.com/component: designerauthoring
  name: ${DESIGNER_INSTANCE_NAME}
spec:
  authentication:
    integrationKeycloak:
      enabled: true
  authorization:
    integrationKeycloak:
      enabled: true
  couchdb:
    replicas: 1
    storage:
      size: 10Gi
      type: persistent-claim
      class: ${OCP_BLOCK_STORAGE}
  designerFlowsOperationMode: local
  designerMappingAssist:
    enabled: true
    incrementalLearning:
      schedule: Every 15 days
      useIncrementalLearning: true
      storage:
        type: persistent-claim
        class: ${OCP_FILE_STORAGE}
  license:
    accept: true
    license: ${INST_LIC}
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  switchServer:
    name: ${SWITCHSRV_INSTANCE_NAME}
  version: '${INST_VER}'