apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: jgr-ace-bake-cp4i
spec:
  flowType:
    toolkitFlow: true
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: CloudPakForIntegrationNonProduction
  template:
    spec:
      containers:
        - name: runtime
          image:  quay.io/jgomezr/ace-12.0.12.4-r1-jgrcp4i-aceivt:1.0.0
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi     
  replicas: 2
  version: 13.0.2.2-r2