apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  annotations:
    apiconnect-operator/backups-not-configured: 'true'
  labels:
    backup.apiconnect.ibm.com/component: apiconnectcluster
  name: ${INST_NAME}
spec:
  analytics:
    mtlsValidateClient: true
  license:
    accept: true
    license: ${INST_LIC}
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  portal:
    mtlsValidateClient: true
  profile: ${INST_PROFILE}
  version: ${INST_VER}
  storageClassName: ${OCP_BLOCK_STORAGE}
  management:
    discovery:
      enabled: true
      proxyCollectorEnabled: true
    governance:
      enabled: true
    testAndMonitor:
      enabled: true
      autoTestEnabled: true