apiVersion: federatedapimanagement.apiconnect.ibm.com/v1beta1
kind: FederatedAPIManagementCluster
metadata:
  name: ${INST_NAME}
spec:
  version: ${INST_VER}
  profile: n1xc3.m4
  analyticsRef: 
    name: ${A7S_NAME}
    namespace: ${DNS_NAME}
  uiEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: fam.${STACK_HOST}
        secretName: fam-ui-endpoint
  adminEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: api.fam.${STACK_HOST}
        secretName: fam-admin-endpoint
  adminClientSubjectDN: CN=federatedapimanagement-admin-client,O=cert-manager
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  license:
    accept: true
    use: nonproduction
    license: ${INST_LIC}